name: Build and publish docker images

on:
  push:
    branches: [main]

jobs:
  clang:
    strategy:
      fail-fast: false
      matrix:
        version: [6, 7, 8, 9, 10, 11, 12]

    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/foonathan/clang
    steps:
      - name: Log-in
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: foonathan
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build --build-arg LLVM_VERSION=${{ matrix.version }}.0.0 --tag $IMAGE:${{ matrix.version }} $GITHUB_WORKSPACE/clang/
      - name: Publish image
        run: docker push $IMAGE:${{ matrix.version }}

