name: Build and publish docker images

on:
  push:
    branches: [main]

jobs:
  clang:
    strategy:
      matrix:
        version:
          - [6, "6.0.1"]
          - [7, "7.1.0"]
          - [8, "8.0.1"]
          - [9, "9.0.1"]
          - [10, "10.0.1"]
          - [11, "11.1.0"]
          - [12, "12.0.1"]
          - [13, "13.0.0"]

    runs-on: ubuntu-latest
    steps:
      - name: Log-in
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: foonathan
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2

     - name: Build image
       run: docker build --build-arg LLVM_VERSION=${{ matrix.version[1] }} --tag foonathan/clang:${{ matrix.version[0] }} $GITHUB_WORKSPACE/clang/
     - name: Publish image
       run: docker push ghcr.io/foonathan/clang:${{ matrix.version[0] }}


