name: Build and publish docker images

on:
  push:
    branches: [main]

jobs:
  clang:
    strategy:
      fail-fast: false
      matrix:
        version:
          - {tag: 6, debian: buster, llvm: "6.0.1"}
          - {tag: 7, debian: buster, llvm: "7.0.1"}
          - {tag: 8, debian: buster, llvm: "8.0.0"}
          - {tag: 9, debian: buster, llvm: "9.0.0"}
          - {tag: 10, debian: buster, llvm: "10.0.0"}
          - {tag: 11, debian: bullseye, llvm: "11.0.0"}
          - {tag: 12, debian: bullseye, llvm: "12.0.0"}
          - {tag: 13, debian: bullseye, llvm: "13.0.0"}
          - {tag: 14, debian: bullseye, llvm: "14.0.0"}
          - {tag: 15, debian: bullseye, llvm: "15.0.6"}
          - {tag: 16, debian: bookworm, llvm: "16.0.4"}

    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/foonathan/clang:${{ matrix.version.tag }}
    steps:
      - name: Log-in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: foonathan
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker buildx build --push \
             --build-arg DEBIAN_VERSION=${{ matrix.version.debian }} --build-arg LLVM_VERSION=${{ matrix.version.llvm }} \
             --platform linux/amd64,linux/arm64/v8 --tag $IMAGE -f $GITHUB_WORKSPACE/clang/Dockerfile .

      - name: Test image
        run: |
          cat $GITHUB_WORKSPACE/test/build.sh | \
          docker run -v "$GITHUB_WORKSPACE/test:/src" -i $IMAGE /bin/bash

  gcc:
    strategy:
      fail-fast: false
      matrix:
        version: [7, 8, 9, 10, 11, 12, 13]

    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/foonathan/gcc:${{ matrix.version }}
    steps:
      - name: Log-in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: foonathan
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker buildx build --push \
             --build-arg GCC_VERSION=${{ matrix.version }} \
             --platform linux/amd64,linux/arm64/v8 --tag $IMAGE -f $GITHUB_WORKSPACE/gcc/Dockerfile .

      - name: Test image
        run: |
          cat $GITHUB_WORKSPACE/test/build.sh | \
          docker run -v "$GITHUB_WORKSPACE/test:/src" -i $IMAGE /bin/bash

